"""empty message

Revision ID: b1695cff6446
Revises: c9cfc5dd79eb
Create Date: 2019-06-14 20:49:53.733561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1695cff6446'
down_revision = 'c9cfc5dd79eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecasts_datetime', table_name='forecasts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_forecasts_datetime', 'forecasts', ['datetime'], unique=False)
    # ### end Alembic commands ###
