"""empty message

Revision ID: 303d03a880ab
Revises: c9cfc5dd79eb
Create Date: 2019-06-14 20:47:06.206714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303d03a880ab'
down_revision = 'b1695cff6446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_forecasts_datetime', table_name='forecasts')
    op.drop_column('forecasts', 'year')
    op.drop_column('forecasts', 'weekday')
    op.drop_column('forecasts', 'month')
    op.drop_column('forecasts', 'day')
    op.drop_column('forecasts', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forecasts', sa.Column('day', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forecasts', sa.Column('month', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forecasts', sa.Column('weekday', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('forecasts', sa.Column('year', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index('ix_forecasts_datetime', 'forecasts', ['datetime'], unique=False)
    # ### end Alembic commands ###
