"""empty message

Revision ID: 54985083e578
Revises: 5fc58dace193
Create Date: 2019-06-30 15:01:38.744068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54985083e578'
down_revision = '5fc58dace193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('historicals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicals',
    sa.Column('drybulb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dewpoint', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relative_humidity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.create_table('stations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stations_pkey')
    )
    # ### end Alembic commands ###
