"""empty message

Revision ID: 5fc58dace193
Revises: ab009d5ba9f3
Create Date: 2019-06-20 12:55:35.973209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc58dace193'
down_revision = 'ab009d5ba9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('retrieval_time', sa.DateTime(), nullable=True))
    sa.PrimaryKeyConstraint('datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'retrieval_time')
    # ### end Alembic commands ###
