"""empty message

Revision ID: 6f33c1aa705f
Revises: 
Create Date: 2019-05-23 19:15:13.878191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f33c1aa705f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('forecasttime', sa.DateTime(), nullable=True),
    sa.Column('drybulb', sa.Integer(), nullable=True),
    sa.Column('wetbulb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicals',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('drybulb', sa.Integer(), nullable=True),
    sa.Column('wetbulb', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('historicals')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
