"""empty message

Revision ID: 8368549842c3
Revises: 6f33c1aa705f
Create Date: 2019-06-01 14:36:01.551872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8368549842c3'
down_revision = '6f33c1aa705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicals', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('dewpoint', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('hmdx', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('relative_humidity', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('stn_press_kpa', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('time', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('visibility_km', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('weather', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('wind_chill', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('wind_dir_10s_deg', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('wind_spd_kmh', sa.Integer(), nullable=True))
    op.add_column('historicals', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('historicals', 'wetbulb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicals', sa.Column('wetbulb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('historicals', 'year')
    op.drop_column('historicals', 'wind_spd_kmh')
    op.drop_column('historicals', 'wind_dir_10s_deg')
    op.drop_column('historicals', 'wind_chill')
    op.drop_column('historicals', 'weather')
    op.drop_column('historicals', 'visibility_km')
    op.drop_column('historicals', 'time')
    op.drop_column('historicals', 'stn_press_kpa')
    op.drop_column('historicals', 'relative_humidity')
    op.drop_column('historicals', 'month')
    op.drop_column('historicals', 'hmdx')
    op.drop_column('historicals', 'dewpoint')
    op.drop_column('historicals', 'day')
    # ### end Alembic commands ###
