"""empty message

Revision ID: 9f25ac91b02e
Revises: a83410346c3f
Create Date: 2019-06-19 22:16:44.077789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f25ac91b02e'
down_revision = 'a83410346c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecasts', 'dewpoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('dewpoint', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
