"""empty message

Revision ID: a83410346c3f
Revises: c9cfc5dd79eb
Create Date: 2019-06-18 10:44:20.089697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a83410346c3f'
down_revision = 'c9cfc5dd79eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecasts', sa.Column('id', sa.DateTime(), nullable=False))
    op.drop_column('forecasts', 'forecasttime')
    op.drop_column('forecasts', 'datetime')
    op.add_column('historicals', sa.Column('id', sa.DateTime(), nullable=False))
    op.drop_column('historicals', 'year')
    op.drop_column('historicals', 'wind_dir_10s_deg')
    op.drop_column('historicals', 'day')
    op.drop_column('historicals', 'month')
    op.drop_column('historicals', 'time')
    op.drop_column('historicals', 'wind_spd_kmh')
    op.drop_column('historicals', 'wind_chill')
    op.drop_column('historicals', 'weather')
    op.drop_column('historicals', 'stn_press_kpa')
    op.drop_column('historicals', 'visibility_km')
    op.drop_column('historicals', 'datetime')
    op.drop_column('historicals', 'hmdx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicals', sa.Column('hmdx', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('historicals', sa.Column('visibility_km', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('stn_press_kpa', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('weather', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('wind_chill', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('wind_spd_kmh', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('wind_dir_10s_deg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('historicals', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('historicals', 'id')
    op.add_column('forecasts', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('forecasts', sa.Column('forecasttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('forecasts', 'id')
    # ### end Alembic commands ###
