"""empty message

Revision ID: ab009d5ba9f3
Revises: 9f25ac91b02e
Create Date: 2019-06-19 23:43:16.136719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab009d5ba9f3'
down_revision = '9f25ac91b02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currents',
    sa.Column('id', sa.DateTime(), nullable=False),
    sa.Column('drybulb', sa.Integer(), nullable=True),
    sa.Column('relative_humidity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currents')
    # ### end Alembic commands ###
