"""empty message

Revision ID: c9cfc5dd79eb
Revises: 
Create Date: 2019-06-14 18:58:16.784741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cfc5dd79eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('forecasttime', sa.DateTime(), nullable=True),
    sa.Column('drybulb', sa.Integer(), nullable=True),
    sa.Column('dewpoint', sa.Integer(), nullable=True),
    sa.Column('relative_humidity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_table('historicals',
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('drybulb', sa.Integer(), nullable=True),
    sa.Column('dewpoint', sa.Integer(), nullable=True),
    sa.Column('relative_humidity', sa.Integer(), nullable=True),
    sa.Column('wind_dir_10s_deg', sa.Integer(), nullable=True),
    sa.Column('wind_spd_kmh', sa.Integer(), nullable=True),
    sa.Column('visibility_km', sa.Integer(), nullable=True),
    sa.Column('stn_press_kpa', sa.Integer(), nullable=True),
    sa.Column('hmdx', sa.Integer(), nullable=True),
    sa.Column('wind_chill', sa.Integer(), nullable=True),
    sa.Column('weather', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    op.drop_table('historicals')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
